In [4]:
import os
# os.chdir('C:/Users/ALBANY PC/Desktop/FINAL YEAR PROJECT/Albany MRS')
os.chdir(r"C:\Users\DELL\Documents\FINAL_FINAL FINAL_PROJECT_APPLICATION/Streamlit_App")
import json
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [5]:
import pandas as pd
 # Import dataset to Data Frame
data = pd.read_csv("./Data/movie_metadata.csv")
data.head(10)

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0
5,Color,Andrew Stanton,462.0,132.0,475.0,530.0,Samantha Morton,640.0,73058679.0,Action|Adventure|Sci-Fi,...,738.0,English,USA,PG-13,263700000.0,2012.0,632.0,6.6,2.35,24000
6,Color,Sam Raimi,392.0,156.0,0.0,4000.0,James Franco,24000.0,336530303.0,Action|Adventure|Romance,...,1902.0,English,USA,PG-13,258000000.0,2007.0,11000.0,6.2,2.35,0
7,Color,Nathan Greno,324.0,100.0,15.0,284.0,Donna Murphy,799.0,200807262.0,Adventure|Animation|Comedy|Family|Fantasy|Musi...,...,387.0,English,USA,PG,260000000.0,2010.0,553.0,7.8,1.85,29000
8,Color,Joss Whedon,635.0,141.0,0.0,19000.0,Robert Downey Jr.,26000.0,458991599.0,Action|Adventure|Sci-Fi,...,1117.0,English,USA,PG-13,250000000.0,2015.0,21000.0,7.5,2.35,118000
9,Color,David Yates,375.0,153.0,282.0,10000.0,Daniel Radcliffe,25000.0,301956980.0,Adventure|Family|Fantasy|Mystery,...,973.0,English,UK,PG,250000000.0,2009.0,11000.0,7.5,2.35,10000

In [6]:
# Use the four colums below ('genres','movie_title','imdb_score', 'movie_imdb_link').
#Create a dataframe for the required columns

df = data[['genres','movie_title','imdb_score', 'movie_imdb_link']].copy()
df.head(15)

,genres,movie_title,imdb_score,movie_imdb_link
0,Action|Adventure|Fantasy|Sci-Fi,Avatar,7.9,http://www.imdb.com/title/tt0499549/?ref_=fn_t...
1,Action|Adventure|Fantasy,Pirates of the Caribbean: At World's End,7.1,http://www.imdb.com/title/tt0449088/?ref_=fn_t...
2,Action|Adventure|Thriller,Spectre,6.8,http://www.imdb.com/title/tt2379713/?ref_=fn_t...
3,Action|Thriller,The Dark Knight Rises,8.5,http://www.imdb.com/title/tt1345836/?ref_=fn_t...
4,Documentary,Star Wars: Episode VII - The Force Awakens ...,7.1,http://www.imdb.com/title/tt5289954/?ref_=fn_t...
5,Action|Adventure|Sci-Fi,John Carter,6.6,http://www.imdb.com/title/tt0401729/?ref_=fn_t...
6,Action|Adventure|Romance,Spider-Man 3,6.2,http://www.imdb.com/title/tt0413300/?ref_=fn_t...
7,Adventure|Animation|Comedy|Family|Fantasy|Musi...,Tangled,7.8,http://www.imdb.com/title/tt0398286/?ref_=fn_t...
8,Action|Adventure|Sci-Fi,Avengers: Age of Ultron,7.5,http://www.imdb.com/title/tt2395427/?ref_=fn_t...
9,Adventure|Family|Fantasy|Mystery,Harry Potter and the Half-Blood Prince,7.5,http://www.imdb.com/title/tt0417741/?ref_=fn_t...
10,Action|Adventure|Sci-Fi,Batman v Superman: Dawn of Justice,6.9,http://www.imdb.com/title/tt2975590/?ref_=fn_t...
11,Action|Adventure|Sci-Fi,Superman Returns,6.1,http://www.imdb.com/title/tt0348150/?ref_=fn_t...
12,Action|Adventure,Quantum of Solace,6.7,http://www.imdb.com/title/tt0830515/?ref_=fn_t...
13,Action|Adventure|Fantasy,Pirates of the Caribbean: Dead Man's Chest,7.3,http://www.imdb.com/title/tt0383574/?ref_=fn_t...
14,Action|Adventure|Western,The Lone Ranger,6.5,http://www.imdb.com/title/tt1210819/?ref_=fn_t...

In [7]:
# Fetch genre of all movies
# loops each row and splits the genres
genres_all_movies = [df.loc[i]['genres'].split('|') for i in df.index]
# type(genres_all_movies)

In [8]:

genres = sorted(list(set([item for sublist in genres_all_movies for item in sublist])))
genres

['Action',
 'Adventure',
 'Animation',
 'Biography',
 'Comedy',
 'Crime',
 'Documentary',
 'Drama',
 'Family',
 'Fantasy',
 'Film-Noir',
 'Game-Show',
 'History',
 'Horror',
 'Music',
 'Musical',
 'Mystery',
 'News',
 'Reality-TV',
 'Romance',
 'Sci-Fi',
 'Short',
 'Sport',
 'Thriller',
 'War',
 'Western']

In [9]:
# Just Checking for the length of genres
len(genres)

26

In [16]:
# Create a list for movie details and movie title seperately
len(genres)
full_data=[]
movie_titles = []

In [17]:
type(df)

pandas.core.frame.DataFrame

In [18]:
genres_all_movies = [df.loc[i]['genres'].split('|') for i in df.index]
genres = sorted(list(set([item for sublist in genres_all_movies for item in sublist])))
len(genres)
full_data=[]
movie_titles = []
df

,genres,movie_title,imdb_score,movie_imdb_link
0,Action|Adventure|Fantasy|Sci-Fi,Avatar,7.9,http://www.imdb.com/title/tt0499549/?ref_=fn_t...
1,Action|Adventure|Fantasy,Pirates of the Caribbean: At World's End,7.1,http://www.imdb.com/title/tt0449088/?ref_=fn_t...
2,Action|Adventure|Thriller,Spectre,6.8,http://www.imdb.com/title/tt2379713/?ref_=fn_t...
3,Action|Thriller,The Dark Knight Rises,8.5,http://www.imdb.com/title/tt1345836/?ref_=fn_t...
4,Documentary,Star Wars: Episode VII - The Force Awakens ...,7.1,http://www.imdb.com/title/tt5289954/?ref_=fn_t...
...,...,...,...,...
5038,Comedy|Drama,Signed Sealed Delivered,7.7,http://www.imdb.com/title/tt3000844/?ref_=fn_t...
5039,Crime|Drama|Mystery|Thriller,The Following,7.5,http://www.imdb.com/title/tt2071645/?ref_=fn_t...
5040,Drama|Horror|Thriller,A Plague So Pleasant,6.3,http://www.imdb.com/title/tt2107644/?ref_=fn_t...
5041,Comedy|Drama|Romance,Shanghai Calling,6.3,http://www.imdb.com/title/tt2070597/?ref_=fn_t...
5042,Documentary,My Date with Drew,6.6,http://www.imdb.com/title/tt0378407/?ref_=fn_t...

In [19]:
df

,genres,movie_title,imdb_score,movie_imdb_link
0,Action|Adventure|Fantasy|Sci-Fi,Avatar,7.9,http://www.imdb.com/title/tt0499549/?ref_=fn_t...
1,Action|Adventure|Fantasy,Pirates of the Caribbean: At World's End,7.1,http://www.imdb.com/title/tt0449088/?ref_=fn_t...
2,Action|Adventure|Thriller,Spectre,6.8,http://www.imdb.com/title/tt2379713/?ref_=fn_t...
3,Action|Thriller,The Dark Knight Rises,8.5,http://www.imdb.com/title/tt1345836/?ref_=fn_t...
4,Documentary,Star Wars: Episode VII - The Force Awakens ...,7.1,http://www.imdb.com/title/tt5289954/?ref_=fn_t...
...,...,...,...,...
5038,Comedy|Drama,Signed Sealed Delivered,7.7,http://www.imdb.com/title/tt3000844/?ref_=fn_t...
5039,Crime|Drama|Mystery|Thriller,The Following,7.5,http://www.imdb.com/title/tt2071645/?ref_=fn_t...
5040,Drama|Horror|Thriller,A Plague So Pleasant,6.3,http://www.imdb.com/title/tt2107644/?ref_=fn_t...
5041,Comedy|Drama|Romance,Shanghai Calling,6.3,http://www.imdb.com/title/tt2070597/?ref_=fn_t...
5042,Documentary,My Date with Drew,6.6,http://www.imdb.com/title/tt0378407/?ref_=fn_t...

In [20]:
# Save file as CSV
df.to_csv('test.csv')

In [21]:
for i in df.index:
    #Append movie title and the index of the movie
    movie_titles.append((df.loc[i]['movie_title'].strip(), i, df.loc[i]['movie_imdb_link'].strip()))
    
    #Add List of genres of the movie (1/10) to movie data
    
    movie_data = [1 if genre in df.loc[i]['genres'].split('|') else 0 for genre in genres]
    
    # Add IMDB score of the movie to main data
    movie_data.append(df.loc[i]['imdb_score'])
    
    #Add record of movie to main data list
    # SK account Number 0222141656
    
    full_data.append(movie_data)

In [22]:
# View the list to see the data stored in each list in the movie_titles  list
print(movie_titles[1])

# print(movie_titles)

("Pirates of the Caribbean: At World's End", 1, 'http://www.imdb.com/title/tt0449088/?ref_=fn_tt_tt_1')

In [23]:
# View the list to see the data stored in each list in the full_data  list
print(full_data[2])

[1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 6.8]

In [24]:
# Exporting the two data as JSON files (JSON dump into Specific Folder)
data_dump = './Data/movie_data.json'
titles_dump = './Data/movie_titles.json'

with open(data_dump, 'w+', encoding = 'utf-8') as f:
    json.dump(full_data, f)
    
with open(titles_dump, 'w+', encoding = 'utf-8') as f:
    json.dump(movie_titles, f)

In [25]:
print(titles_dump)

./Data/movie_titles.json